public class Employee {
   String EmployeeName;
   Integer EmployeeNo;
    integer EmployeeSalary;
  
  public Employee() //Constructor
  {
    EmployeeName = 'sailaja';
    EmployeeNo = 10;
      EmployeeSalary = 1000000;
      
   }
 public void show() //Method
 {
   System.debug('Employee Name is '+ EmployeeName);
   System.debug('Employee No is '+ EmployeeNo);
     System.debug('Employee salary is '+ EmployeeSalary);
     
  }

}