public class HelloWorld21 {
    public static integer num1 =1;
    public integer num2 =2;
    public static integer num3 =1;
    public void numberIncrement(){
        num1++;
        num2++;  
        system.debug(num1);
        system.debug(num2);
    }
    public static integer MultiplyNumbers(integer n1, integer n2){
        num3 = (n1* n2)-num3;
        //system.debug(num2);
        system.debug(num3);
        return num3;
    }

}