public class testIf1 {
   public static void example(){
        Integer Number1 = 20;
        integer Number2 = 20;
        
        if(Number1 < Number2){
            system.debug('number1 is less than number 2');
              
        }else if(Number1 > Number2){
            system.debug('number1 is greater than number 2');
        }else if(Number1 == Number2){
            system.debug('number1 is equal to number 2');
        }  
        } 
   }